name: Build

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  luabuilder:
    name: Lua Builder
    runs-on: ubuntu-latest
    steps:
      - uses: autumngmod/luabuilder